### ISSUE TITLE
Expose `deregister` as a part of public API

### ISSUE THREAD

**Issue by paluh** [robertdp/purescript-resourcet#1]
Hi,

it seems that for scenarios like db transaction management where release action is a failure recovery `ROLLBACK` it could be useful to be able to directly `deregister` cleanup action after a proper `COMMIT`.

* Do you think that it is desirable to expose `deregister` as a part of `Control.Monad.Resource` API?

* Could you please tell me what is your opinion the above approach to transaction handling - am I modeling it correctly?

* Should I provide a PR?

**Comment by robertdp** [comment]
So `deregister` is something I added just to try to get a feel for if it fit or not. It makes sense, but I couldn't immediately come up with a concrete use-case.

Currently the API allows for:
- `acquire` -- acquiring a resource, and registering the cleanup of the resource
- `register` -- registering the cleanup of some resource
- `release` -- manually triggering the cleanup of some registered resource, and
- `deregister` -- removing an registered resources cleanup so that it doesn't run automatically or when `release` is called

Does this idea of `deregister` fit with how you are thinking to use it?

**Comment by robertdp** [comment]
For my opinion about whether that is a good way to handle transactions: well, it depends...

That particular case would require careful use of ResourceT to make sure the cleanup happens at the right time. And this is certainly _possible_, but it seems like the very specific logical requirements of transactions would make a custom transformer like `TransactionT` more appealing.

I mean: what happens if you forget to deregister the failure recovery, the transaction executes successfully and then the failure recovery runs? Some context or transformer with specific knowledge about this requirement would be able to handle this correctly, but ResourceT will just keep going until cleanup time and then execute all the releasers.

**Comment by paluh** [comment]
@robertdp, thanks a lot for exposing this function and for sharing your thoughts on my transaction handling approach. I really, really appreciate your insights! I really want to ask how you picture the design of `TransactionT` but I don't want to over abuse your kindness... :-)

> Does this idea of `deregister` fit with how you are thinking to use it?

I think it does in some sens as described above - I can register cleanup action like `ROLLBACK`. If the whole db operations block ends without problems I can run `COMMIT` and `deregister` release action afterwards.


> I mean: what happens if you forget to deregister the failure recovery, the transaction executes successfully and then the failure recovery runs?

In my case I want to expose only `withTransaction` which is going to be translated into (probably) not exposed operations `begin` and `commit` with a passed computation in between. `commit` will be interpreted into `COMMIT` and `deregister` as described above. I'm going to work on this this week so I could put here some more details...
For sure there are possible corner cases scenarios like error handling on the app level with following another transaction block. So it seems that I have to track not closed transaction in some context too. I wonder if I'm not over complicating this stuff... we will see :-)

**Comment by robertdp** [comment]
If you only want to register effects to run on failure, then there are several ways it could be modelled. Maybe something like:

```purescript
newtype TransactionT m a
  = TransactionT (Connection -> m (Tuple a (m a)))

instance bindTransactionT :: Bind m => Bind (TransactionT m) where
  bind (TransactionT run) f =
    TransactionT \conn -> do
      Tuple a onError <- run conn
      let TransactionT run' = f a
      Tuple b onError' <- run' conn
      pure (Tuple b (onError *> onError'))

runTransactionT :: forall m a. MonadAff m => TransactionT m a -> Connection -> m (Either PGError a)
runTransactionT (TransactionT run) conn = liftAff do
  begin >>= case _ of
      Nothing → do
        Tuple a onError ← run conn `catchError` \jsErr → do
          void $ rollback
          throwError jsErr
        commit >>= case _ of
          Just pgError → onError $> Left pgError
          Nothing → pure (Right a)
      Just pgError → pure (Left pgError)
    where
    begin = execute conn (Query "BEGIN TRANSACTION") Row0
    commit = execute conn (Query "COMMIT TRANSACTION") Row0
    rollback = execute conn (Query "ROLLBACK TRANSACTION") Row0
```

This is pretty basic, and just accumulates some logic to run at every step. Then when the commit fails, it runs.

(`runTransactionT` is mostly lifted from https://github.com/rightfold/purescript-postgresql-client/blob/v3.0.2/src/Database/PostgreSQL.purs#L155-L159)

**Comment by paluh** [comment]
> If you only want to register effects to run on failure, then there are several ways it could be modelled. Maybe something like(...)

This is really cool. Thanks a lot for this nice and clean implementation!

I think that I've to think for a moment before I ask another question... :-)

**Comment by robertdp** [comment]
Closing because the discussion continues elsewhere.
